sudo: false
language: ruby
cache: bundler
script: "bundle exec rspec"
rvm:
  - 1.9.3
  - 2.2.2
  - ruby-head
  - jruby-19mode
  - rbx-2
env:
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
